project_id = "evhorhcqnomgbvvufxnt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:5000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[db]
enabled = true
port = 54322
major_version = 15

[edge_functions]
enabled = true
port = 54323

[functions]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.update-technician-location]
verify_jwt = true

[storage]
enabled = true
port = 54324